# Use a base image with Python pre-installed
FROM python:3.9-slim as builder

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend source code
COPY . .

# Expose port 5000 for Flask server
EXPOSE 5000

# Command to run the Flask server
CMD ["python", "app.py"]
